// <auto-generated />
namespace _72HrChallenge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedCommentsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedCommentsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202111021622348_changedCommentsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
